
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[aws]
disabled=true

[gcloud]
disabled=true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 500

[kubernetes]
disabled=true

[memory_usage]
disabled = false


